# Generated by Django 4.2.5 on 2023-11-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_usermodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone_number',
            field=models.IntegerField(default=' ', unique=True),
        ),
    ]
