version: '3'

services:
  # Django application service
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver"
    container_name: stoke
    image: stoke:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # environment:
    #   - DJANGO_SETTINGS_MODULE=your_project.settings
  #   depends_on:
  #     - db

  # # MySQL service
  # db:
  #   image: mysql:5.7
  #   container_name: mysql-django
  #   environment:
  #     MYSQL_DATABASE: arjuneye
  #   volumes:
  #     - /path/to/your/mysql/data:/var/lib/mysql
